title: "Wrong Today"
author: "Dan Ogawa Lillrank"
description: "Noticing that I'm wrong today is the first step to being less wrong tomorrow."

twitter_username: "DanOL71607511"

collections:
  projects:
    output: true



theme: jekyll-theme-slate
