title: "Harimus blog"
author: "Dan Ogawa Lillrank"
description: "Noticing that I'm wrong today is the first step to being less wrong tomorrow."
url: "https://harimus.github.io/"

twitter_username: "DanOL71607511"

collections:
  projects:
    output: false 

    #remote_theme: pages-themes/tactile@v0.2.0
    #plugins:
    #- jekyll-remote-theme # add this line to the plugins list if you already have one
  
theme: jekyll-theme-slate
